### ISSUE TITLE
Is license really "all rights reserved?"

### ISSUE THREAD

**Issue by simsong** [lithium3141/SwiftDataStructures#6]
This file is posted with a copyright "all rights reserved," which means that people may not incorporate it into any other program. Did you intend that license?

**Comment by rlaferla** [comment]
+1

**Comment by mabundo** [comment]
+1

**Comment by timothyekl** [comment]
Thanks for commenting on this issue, everyone! Sorry I haven't really been responsive to these requests – this project had unfortunately fallen off my radar. I'm happy to make this project available under the MIT License. I hope that suits your needs!

**Comment by simsong** [comment]
Thanks!
